### PR TITLE
Apptracker ui pradeep

### PR DESCRIPTION
**Pull request by pradeepkait85**

### CODE REVIEW

**Comment by pradeepkait85** [comment]
@shahmilanp86 Milan, could you please merge this PR? These has changes that we did over the weekend. Looks like there are conflicts on 3 files. Could you please resolve them? I think you or Gaurav has done changes to same files.

My bad that I didn't create PR on the same day when we did commits.

**Comment by shahmilanp86** [comment]
@pradeepkait85, i am also seeing JAVA files in your pull requests,
Can you please check if you really made those changes

**Comment by pradeepkait85** [comment]
@shahmilanp86 Milan, those were only when I did Pull from develop, I did double check on all my commits, none of them has java changes.

**Comment by shahmilanp86** [comment]
@murthyG , Can you please review i see lot of Java files in pull, i feel there is some kind of merge issues

**Comment by shahmilanp86** [comment]
manually merged changes no need to merge,
the branch seems to be corrupt, please create new branch

**Pull request closed without merging**
